spring:
  jackson:
    default-property-inclusion: non_null
  http:
    encoding:
      charset: UTF-8
      force: true
  datasource:
    url: jdbc:mysql://cp01-ocean-2480.epc.baidu.com:8306/anymock_opensource?serverTimezone=UTC
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: yq01-lizhenxi-dxm.epc.baidu.com
    port: 8331

server:
  port: 8329

anymock:
  core:
    host: 127.0.0.1
    http-interface-port: 8330

fe:
  path: file:///C:/Users/lizhenxi01/Desktop/dxm/open-source/anymock-fe/dist/